name = "blocktrans"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Environment variables for production
# These should be set in Cloudflare Pages dashboard:
# API_URL = "https://api.openai.com/v1/chat/completions"
# MODEL_NAME = "gpt-3.5-turbo"
# API_KEY = "your-api-key-here"

# Note: For Cloudflare Pages, build configuration and environment variables
# are managed through the Cloudflare Dashboard, not in this file.
# This file is primarily used for wrangler CLI commands.
