name = "blocktrans"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Environment variables should be set via:
# 1. Cloudflare Dashboard: Workers & Pages → Your Worker → Settings → Variables
# 2. wrangler CLI: wrangler secret put API_KEY
#
# Required variables:
# - API_URL (environment variable)
# - MODEL_NAME (environment variable)
# - API_KEY (secret - encrypted)
