name = "blocktrans"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Environment variables with default values
# These can be overridden in Cloudflare Dashboard
[vars]
API_URL = "https://api.openai.com/v1/chat/completions"
MODEL_NAME = "gpt-3.5-turbo"

# IMPORTANT:
# - These are DEFAULT values that work out of the box
# - You can override them in Cloudflare Dashboard without losing settings on redeploy
# - API_KEY must always be set as a Secret in Dashboard (never put it here)
#
# To override defaults:
# 1. Go to Cloudflare Dashboard: Workers & Pages → Your Worker → Settings → Variables
# 2. Add variables with same names to override defaults
# 3. API_KEY must be added as Secret type
